print('='*10, 'Cadastro de Funcionários', '='*10)
print('')
print('\t', 'Nome:', 'João')
print('\t', 'Sobrenome:', 'Silva')
print('\t', 'Idade:', 89)
print('\t', 'Salario:', 2975.40)
print('\t', 'Ativo:', True)
print('')
print('='*13, 'Fim do Programa', '='*13)